steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/dmart-digital-api-prod/prod-dmart-in-docker-repo/test-image:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/dmart-digital-api-prod/prod-dmart-in-docker-repo/test-image:$COMMIT_SHA']  
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'prod-dmart-in-as-sth1-cloud-run', '--image', 'asia-south1-docker.pkg.dev/dmart-digital-api-prod/prod-dmart-in-docker-repo/test-image:$COMMIT_SHA', '--region', 'asia-south1', '--platform', 'managed', '--allow-unauthenticated']
images:
- asia-south1-docker.pkg.dev/dmart-digital-api-prod/prod-dmart-in-docker-repo/test-image:$COMMIT_SHA